import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/** Adjectives used for generating cute app names. */
const ADJECTIVES = [
  "happy",
  "gentle",
  "brave",
  "clever",
  "swift",
  "bright",
  "calm",
  "nimble",
  "sleepy",
  "fluffy",
  "wild",
  "tiny",
  "bold",
  "wise",
  "merry",
  "quick",
  "busy",
  "silent",
  "cozy",
  "jolly",
  "playful",
  "friendly",
  "curious",
  "peaceful",
  "silly",
  "dazzling",
  "graceful",
  "elegant",
  "cosmic",
  "whispering",
  "dancing",
  "sparkling",
  "mystical",
  "vibrant",
  "radiant",
  "dreamy",
  "patient",
  "energetic",
  "vigilant",
  "sincere",
  "electric",
  "stellar",
  "lunar",
  "serene",
  "mighty",
  "magical",
  "neon",
  "azure",
  "crimson",
  "emerald",
  "golden",
  "jade",
  "crystal",
  "snuggly",
  "glowing",
  "wandering",
  "whistling",
  "bubbling",
  "floating",
  "flying",
  "hopping",
] as const;

/** Animals used for generating cute app names. */
const ANIMALS = [
  "fox",
  "panda",
  "rabbit",
  "wolf",
  "bear",
  "owl",
  "koala",
  "beaver",
  "ferret",
  "squirrel",
  "zebra",
  "tiger",
  "lynx",
  "lemur",
  "penguin",
  "otter",
  "hedgehog",
  "deer",
  "badger",
  "raccoon",
  "turtle",
  "dolphin",
  "eagle",
  "falcon",
  "parrot",
  "capybara",
  "axolotl",
  "narwhal",
  "wombat",
  "meerkat",
  "platypus",
  "mongoose",
  "chinchilla",
  "quokka",
  "alpaca",
  "chameleon",
  "ocelot",
  "manatee",
  "puffin",
  "shiba",
  "sloth",
  "gecko",
  "hummingbird",
  "mantis",
  "jellyfish",
  "pangolin",
  "okapi",
  "binturong",
  "tardigrade",
  "beluga",
  "kiwi",
  "octopus",
  "salamander",
  "seahorse",
  "kookaburra",
  "gibbon",
  "jackrabbit",
  "lobster",
  "iguana",
  "tamarin",
  "armadillo",
  "starfish",
  "walrus",
  "phoenix",
  "griffin",
  "dragon",
  "unicorn",
  "kraken",
] as const;

/** Verbs used for generating cute app names. */
const VERBS = [
  "run",
  "hop",
  "dash",
  "zoom",
  "skip",
  "jump",
  "glow",
  "play",
  "chirp",
  "buzz",
  "flip",
  "flit",
  "soar",
  "dive",
  "swim",
  "climb",
  "sprint",
  "wiggle",
  "twirl",
  "pounce",
  "bop",
  "spin",
  "hum",
  "roll",
  "blink",
  "skid",
  "kick",
  "drift",
  "bloom",
  "burst",
  "slide",
  "bounce",
  "crawl",
  "sniff",
  "peek",
  "scurry",
  "nudge",
  "snap",
  "swoop",
  "roam",
  "trot",
  "dart",
  "yawn",
  "snore",
  "hug",
  "nap",
  "chase",
  "rest",
  "wag",
  "bob",
  "beam",
  "cheer",
] as const;

/**
 * Picks a random element from a readonly array.
 *
 * @param arr - The array to pick from.
 * @returns A randomly selected element.
 */
function pickRandom<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

/**
 * Generates a cute app name in the format "adjective-animal-verb".
 *
 * @returns A randomly generated three-part name string.
 */
export function generateCuteAppName(): string {
  return `${pickRandom(ADJECTIVES)}-${pickRandom(ANIMALS)}-${pickRandom(VERBS)}`;
}
